apiVersion: v1
kind: Service
metadata:
  name: prodxcloud
spec:
  # externalIPs:
  # - 18.141.186.159
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 80
    nodePort: 31000
  selector:
    app: prodxcloud
  type: LoadBalancer
status:
  loadBalancer: {}